# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Base boosting fast
#' 
#' A fast implementation of the basic boosting function, giving predicted titres for a number of samples for one individual. Note that this version attempts to minimise memory allocations.
#' @family boosting_functions
#' @seealso \code{\link{titre_data_fast}}
ab_kin_normalOLD <- function(predicted_titres, theta, infection_info, vaccination_info, setup_data, indexing, antigenic_maps, other_pars) {
    invisible(.Call('_hcw_study_ab_kin_normalOLD', PACKAGE = 'hcw.study', predicted_titres, theta, infection_info, vaccination_info, setup_data, indexing, antigenic_maps, other_pars))
}

#' Base boosting fast
#' 
#' A fast implementation of the basic boosting function, giving predicted titres for a number of samples for one individual. Note that this version attempts to minimise memory allocations.
#' @family boosting_functions
#' @seealso \code{\link{titre_data_fast}}
ab_kin_vacOLD <- function(predicted_titres, theta, infection_info, vaccination_info, setup_data, indexing, antigenic_maps, other_pars) {
    invisible(.Call('_hcw_study_ab_kin_vacOLD', PACKAGE = 'hcw.study', predicted_titres, theta, infection_info, vaccination_info, setup_data, indexing, antigenic_maps, other_pars))
}

